SET IDENTITY_INSERT [dbo].[Funds_Allocation] ON
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1, 1, N'Course', 40000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (2, 1, N'OEP', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (3, 1, N'OITP', 60000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (4, 2, N'Course', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (5, 2, N'OEP', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (6, 2, N'OITP', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (7, 2, N'SEMINARS', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1048, 1097, N'Courses', 200000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1053, 1097, N'a', 2999)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1101, 1096, N' Courses', 100000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1105, 1096, N' OITP', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1106, 1096, N' OEP', 30000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1107, 1096, N' Seminars', 20000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1112, 1099, N' Courses', 50000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1113, 1099, N' OEP', 23000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1115, 1099, N'OITP', 27000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1119, 1099, N' ', 0)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1120, 1101, N' OITP', 10000)
INSERT INTO [dbo].[Funds_Allocation] ([FAID], [FID], [Pro_Desc], [Amt]) VALUES (1121, 1101, N' OEP', 20000)
SET IDENTITY_INSERT [dbo].[Funds_Allocation] OFF
